const sections = ['프로젝트 개요', '프로젝트 배경', '프로젝트 목표', '주요 기능', '데이터와 질의 흐름', '기대효과와 계획'];
export default function AboutPanel({ onNavigate, presentation, onPresentation }) {
  return <main className="about-panel">
    <header className="about-nav"><span>Behind the Service</span><button className="primary-button" onClick={onPresentation}>{presentation ? '발표 종료 (Esc)' : '발표 모드 ↗'}</button></header>
    <nav className="section-nav" aria-label="발표 목차">{sections.map((title, i) => <a key={title} href={`#story-${i}`}>{String(i + 1).padStart(2, '0')} {title}</a>)}</nav>
    <div className="story-content">
      <section id="story-0" className="story-hero"><div className="eyebrow">TEAM 안전고리 · CAPSTONE PROJECT</div><h1>내 작업에 필요한 안전정보,<br/>연결해서 찾다.</h1><p>개별 사고 자료에서 작업 상황에 맞는 위험요인과 예방대책을 직접 찾아 연결해야 하는 부담을 줄이기 위한 온톨로지 기반 정보 탐색 서비스입니다.</p><div className="hero-word">SafeGori<span>안전고리가 만드는 지식의 연결</span></div></section>
      <section id="story-1"><div className="section-number">01 / BACKGROUND</div><h2>흩어진 사고 자료에서,<br/>작업에 맞는 예방정보로</h2><p>유사한 사고가 반복되는 가운데, 개별 사고 자료에서 자신의 작업 상황과 관련된 위험요인과 예방대책을 직접 찾아 연결해야 하는 부담이 있습니다. SafeGori는 온톨로지로 이 정보의 관계를 구조화하여, 작업 상황에 맞는 안전정보를 탐색하는 과정을 돕고자 합니다.</p><div className="story-cards"><article><h3>탐색의 부담</h3><p>여러 사고 기록을 읽으며 내 작업과 관련된 정보를 찾아야 합니다.</p></article><article><h3>연결의 필요</h3><p>작업 상황·위험요인·예방대책을 함께 이해할 수 있어야 합니다.</p></article><article><h3>온톨로지 기반 탐색</h3><p>정보 간 관계를 따라 필요한 예방정보에 접근하는 것이 목표입니다.</p></article></div></section>
      <section id="story-2"><div className="section-number">02 / OBJECTIVES</div><h2>SafeGori가 지향하는 세 가지</h2><div className="story-cards"><article><h3>관계를 보는 탐색</h3><p>LPG 기반 온톨로지로 사고와 예방 지식의 연결 구조를 표현합니다.</p></article><article><h3>질문으로 찾는 대책</h3><p>자연어 질문을 통해 관련 사고와 예방대책에 접근하는 것을 목표로 합니다.</p></article><article><h3>원본으로 확인하는 근거</h3><p>사고 사례의 원문과 출처를 직접 확인할 수 있습니다.</p></article></div></section>
      <section id="story-3"><div className="section-number">03 / EXPERIENCE</div><h2>직접 살펴보는 주요 기능</h2><div className="story-cards">{[['explore', '온톨로지 전체 탐색', '항목과 관계를 탐색하는 예시 그래프'], ['chat', '안전대책 물어보기', 'Gemini 기본 대화가 연결된 안전 도우미 링키'], ['cases', '사고 사례 조회', '엑셀 원본 기반 검색·필터·상세 조회']].map(([id, title, description]) => <article key={id}><h3>{title}</h3><p>{description}</p><button className="secondary-button" onClick={() => onNavigate(id)}>화면 열기 ↗</button></article>)}</div></section>
      <section id="story-4"><div className="section-number">04 / ARCHITECTURE</div><h2>기록에서 답변까지</h2><p className="status-line">현재 구현: 웹 UI, 엑셀 기반 조회, FastAPI와 Gemini 기본 대화 연결. 사고 데이터·온톨로지 기반 답변은 구현 예정입니다.</p><h3>데이터 적재 흐름 · 계획</h3><div className="flow"><span>엑셀 원본</span><b>→</b><span>정리·검수</span><b>→</b><span>PostgreSQL<small>사고 원본 관리</small></span><b>→</b><span>Neo4j<small>온톨로지 관계 관리</small></span></div><h3>자연어 질의 흐름 · 계획</h3><div className="flow"><span>사용자 질문</span><b>→</b><span>LLM / Cypher 생성</span><b>→</b><span>Neo4j 조회</span><b>→</b><span>근거 기반 답변</span></div><p>현재 사고 사례는 엑셀에서 변환한 데이터로 조회하며, 그래프는 예시 데이터입니다. PostgreSQL·Neo4j 적재와 NL-to-Cypher를 연결하고 Docker 개발 환경을 구성할 예정입니다.</p></section>
      <section id="story-5"><div className="section-number">05 / NEXT STEPS</div><h2>연결의 가치를 검증하기</h2><div className="story-cards"><article><h3>기대효과</h3><p>관련 사고 탐색을 돕고, 예방 정보의 접근성과 답변 근거 확인 경험을 개선하고자 합니다.</p></article><article><h3>구현 계획</h3><p>온톨로지 설계, Neo4j 적재 파이프라인, NL-to-Cypher와 근거 사례 연결을 진행합니다.</p></article><article><h3>평가 계획</h3><p>온톨로지 적용 전·후 답변을 비교하고, 팀에서 검수한 골든셋으로 정확도를 평가할 예정입니다.</p></article></div><footer>안전고리 · SafeGori</footer></section>
    </div>
  </main>;
}
